name: Apply Codesherlock patch
on: { workflow_dispatch: {} }
permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Verify patch exists and normalize line endings
        run: |
          test -f codesherlock-all-fixes.patch
          sed -i 's/\r$//' codesherlock-all-fixes.patch
   
      - name: Sanitize and repair patch
        run: |
          set -e
          test -f codesherlock-all-fixes.patch

          # 1) Strip UTF-8 BOM if present
          sed -i '1s/^\xEF\xBB\xBF//' codesherlock-all-fixes.patch

          # 2) Normalize CRLF to LF
          sed -i 's/\r$//' codesherlock-all-fixes.patch

          # 3) Remove Markdown code fences if they slipped in
          if grep -q '^```' codesherlock-all-fixes.patch; then
            awk 'BEGIN{in=1} /^```/{in = !in; next} in{print}' codesherlock-all-fixes.patch > .patch.clean
            mv .patch.clean codesherlock-all-fixes.patch
          fi

          # 4) Fix missing hunk prefixes (space) in content lines
          #    Between a hunk header and the next 'diff --git', any non-empty
          #    line that doesn't start with space/+/-/\ gets prefixed with a space.
          awk '
            /^diff --git / { in_hunk=0; print; next }
            /^@@ /        { in_hunk=1; print; next }
            {
              if (in_hunk && NF && $0 !~ /^[ +\-\\]/) { print " " $0 }
              else { print }
            }
          ' codesherlock-all-fixes.patch > .patch.fixed && mv .patch.fixed codesherlock-all-fixes.patch

          # Optional: show first lines for debugging
          echo "---- FIRST 40 LINES (post-fix) ----"
          nl -ba codesherlock-all-fixes.patch | sed -n '1,40p'


      - name: Validate patch
        run: |
          git apply --check codesherlock-all-fixes.patch

      - name: Apply patch and commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git switch -c fix/codesherlock-all || git switch fix/codesherlock-all
          git apply --whitespace=fix codesherlock-all-fixes.patch
          git add -A
          git commit -m "Fix: address Codesherlock issues + back-compat routes, RBAC, schema alignments" || echo "No changes to commit"

      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: fix/codesherlock-all
          title: "Fix: Codesherlock issues + back-compat"
          commit-message: "Fix: address Codesherlock issues + back-compat routes, RBAC, schema alignments"
          body: |
            Applies the consolidated patch (validated with git apply --check).
